In [1]:
import pandas as pd
import numpy as np
import requests

In [2]:
pd.__version__

'1.4.3'

In [3]:
url = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv"
response = requests.get(url)

In [4]:
if response.status_code == 200:
    with open("housing.csv", "wb") as f:
        f.write(response.content)
    print("File downloaded successfully.")
else:
    print("Failed to download the file.")


File downloaded successfully.


In [5]:
ls

 Volume in drive C has no label.
 Volume Serial Number is BCC0-49D8

 Directory of C:\Users\KonuTech\ml-zoomcamp\machine-learning-zoomcamp\01-intro

24.09.2023  22:11    <DIR>          .
24.09.2023  22:11    <DIR>          ..
24.09.2023  22:10    <DIR>          .ipynb_checkpoints
17.09.2023  18:17             1˙391 01-what-is-ml.md
17.09.2023  18:17             2˙017 02-ml-vs-rules.md
17.09.2023  18:17             2˙007 03-supervised-ml.md
17.09.2023  18:17             2˙180 04-crisp-dm.md
17.09.2023  18:17             1˙782 05-model-selection.md
24.09.2023  21:58             5˙423 06-environment.md
24.09.2023  21:58             5˙351 07-numpy.md
17.09.2023  18:17             2˙731 08-linear-algebra.md
17.09.2023  18:17               938 09-pandas.md
17.09.2023  18:17               706 10-summary.md
17.09.2023  18:17               465 homework.md
24.09.2023  22:11         1˙423˙529 housing.csv
18.09.2023  22:58            43˙621 HW_01.ipynb
17.09.2023  18:17    <DIR>          images
24

In [6]:
csv_file = "housing.csv"

In [7]:
df = pd.read_csv(csv_file)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [9]:
df.tail()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND

In [10]:
df.shape

(20640, 10)

In [11]:
null_counts = df.isna().sum()

In [12]:
null_counts

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [13]:
df["ocean_proximity"].unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [14]:
len(df["ocean_proximity"].unique())

5

In [15]:
filter_category = "NEAR BAY"

In [16]:
near_bay = df[df["ocean_proximity"] == filter_category]

In [17]:
near_bay.shape

(2290, 10)

In [18]:
near_bay.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [19]:
near_bay.tail()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
19067    -122.45     38.28                20.0       3306.0           503.0   
19068    -122.47     38.29                14.0       3732.0           846.0   
19069    -122.45     38.27                25.0       5024.0           881.0   
19077    -122.49     38.27                 8.0       5092.0           988.0   
19104    -122.51     38.17                 8.0       5875.0          1115.0   

       population  households  median_income  median_house_value  \
19067      1374.0       460.0         5.7984            297600.0   
19068      1277.0       775.0         2.5658            208000.0   
19069      1994.0       838.0         4.2237            262300.0   
19077      1657.0       936.0         3.5625            213200.0   
19104      2808.0      1029.0         3.6392            246300.0   

      ocean_proximity  
19067        NEAR BAY  
19068        NEAR BAY  
19069        NEAR BAY  
19077        NEAR BAY  
19104        NEAR BAY

In [20]:
mean_median_house_value = near_bay["median_house_value"].mean()

In [21]:
mean_median_house_value

259212.31179039303

In [22]:
# Check for missing values in the "total_bedrooms" column
missing_values = df["total_bedrooms"].isnull().sum()
missing_values

207

In [23]:
df["total_bedrooms"].min()

1.0

In [24]:
percentile_25 = df['total_bedrooms'].quantile(0.25)
percentile_25

296.0

In [25]:
df["total_bedrooms"].mean()

537.8705525375618

In [26]:
percentile_75 = df['total_bedrooms'].quantile(0.75)
percentile_75

647.0

In [27]:
df["total_bedrooms"].max()

6445.0

In [28]:
# Fill missing values with the mean
df["total_bedrooms"].fillna(df["total_bedrooms"].mean(), inplace=True)

In [29]:
# Check for missing values in the "total_bedrooms" column
missing_values = df["total_bedrooms"].isnull().sum()
missing_values

0

In [30]:
df["total_bedrooms"].min()

1.0

In [31]:
percentile_25 = df['total_bedrooms'].quantile(0.25)
percentile_25

297.0

In [32]:
df["total_bedrooms"].mean()

537.8705525375617

In [33]:
percentile_75 = df['total_bedrooms'].quantile(0.75)
percentile_75

643.25

In [34]:
df["total_bedrooms"].max()

6445.0

In [35]:
df = pd.read_csv(csv_file)

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [37]:
filter_category = "ISLAND"

In [38]:
island = df[df["ocean_proximity"] == filter_category]

In [39]:
island.shape

(5, 10)

In [40]:
island[["housing_median_age", "total_rooms", "total_bedrooms"]]

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [41]:
selected_columns = island[["housing_median_age", "total_rooms", "total_bedrooms"]]
selected_columns

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [42]:
# Get the underlying NumPy array X
X = selected_columns.values
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [43]:
X.T

array([[  27.,   52.,   52.,   52.,   29.],
       [1675., 2359., 2127.,  996.,  716.],
       [ 521.,  591.,  512.,  264.,  214.]])

In [44]:
help(np.dot)

Help on function dot in module numpy:

dot(...)
    dot(a, b, out=None)
    
    Dot product of two arrays. Specifically,
    
    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).
    
    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.
    
    - If either `a` or `b` is 0-D (scalar), it is equivalent to :func:`multiply`
      and using ``numpy.multiply(a, b)`` or ``a * b`` is preferred.
    
    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.
    
    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of `b`::
    
        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
    
    Parameters
    ----------
    a : array_like
        First argument.
    b : array_like
        Second argument.
    out : 

In [45]:
# Compute matrix-matrix multiplication between the transpose of X and X (XTX)
XTX = np.dot(X.T, X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [46]:
help(np.linalg.inv)

Help on function inv in module numpy.linalg:

inv(a)
    Compute the (multiplicative) inverse of a matrix.
    
    Given a square matrix `a`, return the matrix `ainv` satisfying
    ``dot(a, ainv) = dot(ainv, a) = eye(a.shape[0])``.
    
    Parameters
    ----------
    a : (..., M, M) array_like
        Matrix to be inverted.
    
    Returns
    -------
    ainv : (..., M, M) ndarray or matrix
        (Multiplicative) inverse of the matrix `a`.
    
    Raises
    ------
    LinAlgError
        If `a` is not square or inversion fails.
    
    See Also
    --------
    scipy.linalg.inv : Similar function in SciPy.
    
    Notes
    -----
    
    .. versionadded:: 1.8.0
    
    Broadcasting rules apply, see the `numpy.linalg` documentation for
    details.
    
    Examples
    --------
    >>> from numpy.linalg import inv
    >>> a = np.array([[1., 2.], [3., 4.]])
    >>> ainv = inv(a)
    >>> np.allclose(np.dot(a, ainv), np.eye(2))
    True
    >>> np.allclose(np.dot(ainv, a), 

In [47]:
# Compute the inverse of XTX
XTX_inverse = np.linalg.inv(XTX)
XTX_inverse

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [48]:
# Create an array y with values [950, 1300, 800, 1000, 1300]
y = np.array([950, 1300, 800, 1000, 1300])
y

array([ 950, 1300,  800, 1000, 1300])

In [49]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y to get w
w = np.dot(np.dot(XTX_inverse, X.T), y)
w

array([23.12330961, -1.48124183,  5.69922946])

In [50]:
# The value of the last element of w is the answer
last_element_of_w = w[-1]
last_element_of_w

5.699229455065586